version: '3.3'

services:
  db:
    image: antoursdb:latest
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: antourswordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: 123456
  
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "4000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: 123456
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - .:/var/www/html
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 4001:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: antourswordpress
      PMA_HOST: db
volumes:
  dbdata: